name: Run Tender On Times Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # Runs every day at 01:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tender Bot
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python scripts/tender_bot.py

      - name: Upload downloaded files
        if: always()  # Run even if the bot fails
        uses: actions/upload-artifact@v4
        with:
          name: tender_downloads
          path: /home/runner/downloads
          if-no-files-found: ignore
